baseURL = 'https://kondickypraha.cz'
languageCode = 'cs'
title = 'Kondiční jízdy Praha - Svoboda'
[params]
  description = 'Potřebujete kondiční jízdy? Naučíme Vás, jak bezpečně a rychle parkovat, seznámíte se s novými pravidly silníčního provozu a nebudete se bát vyjet do hustého centra Prahy.'